### ISSUE TITLE
The migration script on the BE project

### ISSUE THREAD

**Issue by nguyenhung1903** [Dummy-WAD/dka-shop-be#12] opened 2024-10-09 10:16 UTC
Please update the NodeJS to version 22.9. 
---
We have some problems with the model and API codes in this code. The migration code follows ES6, and the current API code follows the ESM and CommonJS or the opposite case.
---
Hmm,... So, in this case, we need to create a package.json file for migration only (I have created some scripts to automate that, actually)

---
Don't worry, this is not an issue 👍 , I want to notify you to know that.

**Comment by lightx26** [comment] 2024-10-09 17:22
The issue is addressed by using migration.bat script

**Closed by lightx26** 2024-10-09 17:22 UTC
